debug build

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -45,10 +45,8 @@ jobs:
           cp Conversion.js public/Conversion.js
           cp libantimony.js public/libantimony.js   
 
-      - name: Debug working directory
-        run: |
-          pwd
-          ls -lah
+      - name: Check public directory
+        run: ls -lah public || echo "public/ folder is missing"
 
       - name: Build
         run: npm run build
